### ISSUE TITLE
Only two albums to play

### ISSUE THREAD

**Issue by EgrettaGarzetta** [n76/Symphony#15] opened 2018-09-01 10:07 UTC
Don't know what I'm missing, but there are more than two albums in the folder where these two are.

**Comment by n76** [comment] 2018-09-01 14:55
Symphony, like many but not all other music player apps, gets its album information from the Android media management system. So if you are only seeing two albums in Symphony then the Android media management system is only seeing two albums.

The Android media management system does not look at folders when determining what an album consists of. It looks at the metadata within each file where it also finds things like artist, composer, track name (possibly different from file name) and track number (within an album), etc.

You may wish to examine your music files with an app that allows you to examine and edit the metadata to assure that all the desired fields within the track(s) are properly set. There are some Android apps that allow you to examine and edit music metadata on the phone but I did not have much luck with them. So I use iTunes on my laptop to organize my tracks into albums, properly set the composer, artist, etc. Then I use SyncThing to assure that my phone has a duplicate of my iTunes library. Only hitch for me is that SyncThing does not notify the Android Media Manager that it should rescan when something changes in my music library. But there are ways to trigger a scan on Android to work around that issue.

**Closed as completed by n76** 2018-09-01 14:55 UTC

**Comment by EgrettaGarzetta** [comment] 2018-09-02 16:07
Thanks, I'll look again and I'm sure that's going to help.

D
